### ISSUE TITLE
facing problem in loading from composer  "saintsystems/odata-client": "0.1.*"

### ISSUE THREAD

**Issue by dushyantfst** [saintsystems/odata-client-php#1]
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package saintsystems/odata-client could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

**Comment by anderly** [comment]
Hi there. Apologies for the delay. The composer package wasn't published. We just published the dev-master version so please reference that version for now instead of 0.1.0.

**Comment by buttflattery** [comment]
@anderly i use `composer require "saintsystems/odata-client": "@dev-master"` but getting the following exception 
 

>  [InvalidArgumentException]
>   Could not find package @dev-master.
> 
>   Did you mean one of these?
>       devmastersbv/imap
>       wyrihaximus/dev-master
>       devmastersbv/yii2-jwt
>       webberdoo/frework
>       devmastersbv/pthreads
> 

Am i not providing the version properly?

**Comment by anderly** [comment]
Should be working now.

Use `^0.2.1` for version constraint.
