### ISSUE TITLE
PHP v8.1: Deprecated: Return type of SaintSystems\OData\Entity::offsetExists($offset) should either be compatible with

### ISSUE THREAD

**Issue by Axent96** [saintsystems/odata-client-php#100]
Deprecated: Return type of SaintSystems\OData\Entity::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in

**Comment by Axent96** [comment]
more messages:

- Deprecated: Return type of SaintSystems\OData\Entity::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/saintsystems/odata-client/src/Entity.php on line 819
- Deprecated: Return type of SaintSystems\OData\Entity::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/saintsystems/odata-client/src/Entity.php on line 830
- Deprecated: Return type of SaintSystems\OData\Entity::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/saintsystems/odata-client/src/Entity.php on line 842
- Deprecated: Return type of SaintSystems\OData\Entity::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in .../vendor/saintsystems/odata-client/src/Entity.php on line 853

**Comment by cslevy** [comment]
I created a pull request to fix the issues: https://github.com/saintsystems/odata-client-php/pull/113

**Comment by anderly** [comment]
Closed by #113
