### ISSUE TITLE
Keys starting with an underscore are removed from the response

### ISSUE THREAD

**Issue by johanmolen** [saintsystems/odata-client-php#102]
Is there a reason for removing keys which start with an underscore?
https://github.com/saintsystems/odata-client-php/blob/master/src/Entity.php#L701

Is there a way to override this behaviour?

**Comment by johanmolen** [comment]
I think this behaviour is copied from Laravel. But this way odata keys starting with an underscore are removed :(

**Comment by johanmolen** [comment]
Someone?

**Comment by itspoonmkohv** [comment]
This is an issue for me too - SAP S/4Hana Cloud API expands with underscore. So this library is currently not suitable for SAP Queries. 

Here is an example for typical SAP query
/sap/opu/odata4/sap/api_product/srvd_a2x/sap/product/0001/Product?$top=50&$expand=_ProductDescription,_ProductPlant

**Comment by anderly** [comment]
@johanmolen, @itspoonmkohv yes, this is copied from Laravel Eloquent Model class. Confirming that there are no unintended consequences of removing this, but I think we'll be able to remove this to make it work.

**Comment by tavy315** [comment]
Perhaps https://github.com/laravel/framework/issues/6630 helps?

**Comment by anderly** [comment]
Fixed in [Release 0.7.4](../releases/tag/0.7.4)
