### ISSUE TITLE
Add compatibility with laravel 9.

### ISSUE THREAD

**Issue by Nickvandrunen** [saintsystems/odata-client-php#103]
` Problem 1
    - Root composer.json requires saintsystems/odata-client ^0.6.1 -> satisfiable by saintsystems/odata-client[0.6.1].
    - saintsystems/odata-client 0.6.1 requires illuminate/support ^5.8 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.`

**Comment by anderly** [comment]
Closed by #105
