### ISSUE TITLE
AtomPub/XML support

### ISSUE THREAD

**Issue by CodeDestroyer** [saintsystems/odata-client-php#13]
`SaintSystems\OData\ODataResponse` assumes a json response, any plans for support?

**Comment by anderly** [comment]
@CodeDestroyer no current plans for AtomPub/XML support, but we'd welcome a PR if you'd like to contribute. Best bet would probably be an `ODataXmlResponseProcessor` class or similar abstraction that could be set on the `ODataClient` and defaults to a `ODataJsonResponseProcessor`.

**Comment by anderly** [comment]
Closed due to non-activity and no PRs. We welcome a PR to add support for this, but it is not currently on our roadmap.
