### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by mcatieno** [saintsystems/odata-client-php#131]
So am trying to run composer require saintsystems/odata-client but this fails with these errors:
Problem 1
    - saintsystems/odata-client[0.2.0, ..., 0.2.6] require guzzlehttp/guzzle ^6.2 -> found guzzlehttp/guzzle[6.2.0, ..., 6.5.8] but it conflicts with your root composer.json require (^7.5).
    - saintsystems/odata-client[0.3.0, ..., 0.5.2] require php ^7.2 -> your php version (8.1.12) does not satisfy that requirement.
    - saintsystems/odata-client 0.6.0 requires php ^7.3 -> your php version (8.1.12) does not satisfy that requirement.
    - saintsystems/odata-client 0.6.1 requires illuminate/support ^5.8 || ^6.0 || ^7.0 || ^8.0 -> found illuminate/support[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - saintsystems/odata-client[0.6.2, ..., 0.6.3] require illuminate/support ^5.8 || ^6.0 || ^7.0 || ^8.0 || ^9.0 -> found illuminate/support[v5.8.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.7] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires saintsystems/odata-client * -> satisfiable by saintsystems/odata-client[0.2.0, ..., 0.6.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require saintsystems/odata-client:*" to figure out if any version is installable, or "composer require saintsystems/odata-client:^2.1" if you know which you need.

**Comment by anderly** [comment]
Should be fixed now.

**Comment by anderly** [comment]
This is available in [Release 0.6.4](../releases/tag/0.6.4)
