### ISSUE TITLE
Build system for odata-client-php

### ISSUE THREAD

**Issue by gRegorLove** [saintsystems/odata-client-php#136]
It appears that Travis CI builds haven't run for a [couple years](https://app.travis-ci.com/github/saintsystems/odata-client-php/builds), I'm guessing due to their pricing changes. It would be nice to get those running again or switch to Github Actions. I think that would help catch issues like [#134](https://github.com/saintsystems/odata-client-php/issues/134) before new releases.

(Originally published at: https://gregorlove.com/2023/07/build-system-for-odata-client-php/)

**Comment by anderly** [comment]
Closed by 0c4d46f
