### ISSUE TITLE
Using `mixed` type breaks PHP7.4 compatibility

### ISSUE THREAD

**Issue by n8rowley** [saintsystems/odata-client-php#139]
Continuation of closed issue #134. Seems we just missed removing 1 instance.

I've updated my code to use 0.6.4, but I found one more issue. The `offsetGet()` function is declaring its return type as `mixed` and it causes PHP7.4 to error out. PR #138 fixes the issue for me.

**Comment by anderly** [comment]
Closed by b05a995

**Comment by anderly** [comment]
Fixed in [Release 0.6.5](../releases/tag/0.6.5)
