### ISSUE TITLE
Separate commits for different tasks

### ISSUE THREAD

**Issue by cweiske** [saintsystems/odata-client-php#144]
I just upgraded from 0.6 to 0.7.1 and things broke. During debugging I wanted to see the changes in `ODataRequest::execute()`, did a `git blame` and found commit c34498a1c01a3ddac2ff5b5045f72da5cc2d27b9.

Unfortunately this commit mixes up
- Whitespace changes (newlines)
- Code style changes
- Actual code changes that modify the library's behavior

It would be really nice if you would split those changes in the future in separate commits (e.g. via `git add -p`) so that it's easier to see what changed. Looking at the commits is the only thing we can do as long as there are no upgrade guides, so they are important.

**Comment by anderly** [comment]
@cweiske, you can see the separate commits via the [PR](../pull/142), but these were squashed with the PR merge.
