### ISSUE TITLE
Guid primitive literals non compliant with OASIS OData url conventions (v4.0)

### ISSUE THREAD

**Issue by kinekt4** [saintsystems/odata-client-php#155]
I'm using a REST api and have been successful filtering by string and decimals etc.

But when filtering a guid column I get a `400 Bad Response` with the following error:

> A binary operator with incompatible types was detected. Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'. 

I'm currently filtering like this:

    $item = $odataClient->from('Item')->where('id', '=', 'ec11-80f1-0022489308a6')->get();

I see that the issue is related to the single quotes being added to the value in `Grammar::prepareValue()`.

To prevent single quotes being added, it seems I have to explicitly define the type as a prefix `Grammar::isSpecialPrimitiveDataType()`

    return preg_match("/^(binary|datetime|guid|time|datetimeoffset)(\'[\w\:\-\.]+\')$/i", $value);

So I've modified the guid value to something like this:

    $item = $odataClient->from('Item')->where('id', '=', "guid'ec11-80f1-0022489308a6'")->get();

Which resulted in a different error.

Can anyone suggest anything else I can try?

Thanks!

- odata-client: `v0.7.3`
- REST API: MS Dynamics 365 (D365)

**Edit**
- It seems that the API I'm using (MS Dynamics 365) doesn't support the `guid'<value>'` syntax
- And there's no way to passthrough the value without the value being stringified by this library (I believe)
- I'm proposing a possible fix here:
- https://github.com/saintsystems/odata-client-php/pull/156

**Edit 02**
- I just noticed this PR:
- https://github.com/saintsystems/odata-client-php/pull/105
- Which deals with passing through the whole raw statement
--- 

### Rest API
Test done via Postman
| Filter     | Response      |
| ------------- | ------------- |
| `id eq 'ec11-80f1-0022489308a6'` | **Error**: A binary operator with incompatible types was detected. <br>Found operand types 'Edm.Guid' and 'Edm.String' for operator kind 'Equal'. |
| `id eq guid'ec11-80f1-0022489308a6'` | **Error**: Unrecognized 'Edm.String' literal...  |
| `id eq ec11-80f1-0022489308a6` | **OK** |

**Comment by kinekt4** [comment]
- OData Documentation v4.02
- https://docs.oasis-open.org/odata/odata/v4.02/csd01/part2-url-conventions/odata-v4.02-csd01-part2-url-conventions.html#PrimitiveLiterals
- `GuidValue eq 01234567-89ab-cdef-0123-456789abcdef`

**Comment by kinekt4** [comment]
- I just found this issue which relates to what I'm trying to achieve: 
- #76; and this PR
- https://github.com/saintsystems/odata-client-php/pull/105

**Comment by kinekt4** [comment]
Whereas PR #105 allows users to pass through the whole raw expression; eg.

    $whereRaw = "id eq ec11-80f1-0022489308a6";
    $item = $odataClient->from('Item')->whereRaw($whereRaw)->get();

My PR #156 only aims to pass through the raw value, while maintaining the regular syntax as before

    $item = $odataClient->from('Item')->where('id', '=', "raw'ec11-80f1-0022489308a6'")->get();

**Comment by kinekt4** [comment]
I found my solution in #137, I should do this instead (undocumented):

    $item = $odataClient->from('Item')->whereKey('ec11-80f1-0022489308a6')->get();

**Comment by anderly** [comment]
Will see about updating samples and docs with this.

**Comment by anderly** [comment]
@kinekt4, also curious if the following would work for your case if it's an ID/PK field:

```php
    $odataClient->from('Item')->find('ec11-80f1-0022489308a6');
```
