### ISSUE TITLE
Please implement "order" method

### ISSUE THREAD

**Issue by cmanley** [saintsystems/odata-client-php#16]
In Builder.php there are references to "order" but it seems the "order" method hasn't been implemented yet.

**Comment by anderly** [comment]
@cmanley noted. This is still on the to-do list.

**Comment by anderly** [comment]
Fixed by 47db6415f893928523a03a62c006e08e049c6c95

**Comment by anderly** [comment]
Fixed by 47db6415f893928523a03a62c006e08e049c6c95
