### ISSUE TITLE
Undefined Method

### ISSUE THREAD

**Issue by thinkerytim** [saintsystems/odata-client-php#2]
I'm running into an issue for `Call to undefined method SaintSystems\OData\Entity::getRelationValue()` in line 1344 of the `Entity` class.

**Comment by moazam1** [comment]
I am having same issue. @thinkerytim did you find any solution?

**Comment by anderly** [comment]
@thinkerytim @moazam1 getRelationValue is not yet implemented to obtain related properties. I'll leave this open to track the status of the issue.

**Comment by anderly** [comment]
Fixed by ab1b99f830bfd6ee5ac1875aeb58a4424b8b7314
