### ISSUE TITLE
No quotes around specific fields

### ISSUE THREAD

**Issue by jeffreyvr** [saintsystems/odata-client-php#20]
When using the where function on for example a integer-field, you'll get the following error because quotes are automatically set around the value:

A binary operator with incompatible types was detected. Found operand types 'Edm.Int32' and 'Edm.String' for operator kind 'Equal'.

Is there an option to prevent those quotes from being added for specific fields?

**Comment by anderly** [comment]
Please try with `^0.2.2` and let me know if this is still an issue.
