### ISSUE TITLE
Question about @odata.nextLink

### ISSUE THREAD

**Issue by drblitz-weblab** [saintsystems/odata-client-php#22]
For example we have request like this 

`$people = $odataClient->from('People')->take(2)->get();`

How I can get access to @odata.nextLink

**Comment by stefantalen** [comment]
@t3Golden Did you figure this out?

**Comment by Cabag** [comment]
Any process on this yet? Currently, I am doing a count() first, and then I page through the results doing a skip which is a nasty workaround since OData is providing the next page.
Would be really great to have the @odata.nextLink property available somehow.

**Comment by mschop** [comment]
:+1:  I just ran into that problem as well. This issue is open for 4 years now. Is there a solution now? Otherwise I will build an own implementation.

**Comment by glaszig** [comment]
i. need. this.

working with an api that enforces pagination. can you provide your wip so we can take it from there, please?

**Comment by anderly** [comment]
Setting `$odataClient->setEntityReturnType(false);` will allow you to get the full `ODataResponse` object, from which you can then call [getSkipToken](../blob/master/src/ODataResponse.php#L171),

**Comment by anderly** [comment]
Please take a look at [PR142](../pull/142) which adds support for native paging over the paginated OData response using `LazyCollection` via new `cursor` methods on the `Builder` and `ODataClient`.

**Comment by anderly** [comment]
Updated wiki with paging examples [here](../wiki/Example-Calls#page-through-a-collection).
