### ISSUE TITLE
Package problem with carbon in laravel 5.8

### ISSUE THREAD

**Issue by nsnvglobal** [saintsystems/odata-client-php#34]
When I run composer command it fail because of carbon package. It's it possible to edit the version of carbon so it will work in the newest version of laravel?

------
require saintsystems/odata-client
Using version ^0.2.4 for saintsystems/odata-client
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for saintsystems/odata-client ^0.2.4 -> satisfiable by saintsystems/odata-client[0.2.4].
    - Conclusion: remove nesbot/carbon 2.20.0
    - Conclusion: don't install nesbot/carbon 2.20.0
    - saintsystems/odata-client 0.2.4 requires nesbot/carbon ^1.22 -> satisfiable by nesbot/carbon[1.22.0, 1.22.1, 1.23.0, 1.24.0, 1.24.1, 1.24.2, 1.25.0, 1.25.1, 1.25.3, 1.26.0, 1.26.1, 1.26.2, 1.26.3, 1.26.4, 1.26.5, 1.26.6, 1.27.0, 1.28.0, 1.29.0, 1.29.1, 1.29.2, 1.30.0, 1.31.0, 1.31.1, 1.32.0, 1.33.0, 1.34.0, 1.34.1, 1.34.2, 1.34.3, 1.34.4, 1.35.0, 1.35.1, 1.36.0, 1.36.1, 1.36.2, 1.37.0, 1.37.1, 1.38.0, 1.38.1, 1.38.2, 1.38.3, 1.38.4, 1.39.0].
    - Can only install one of: nesbot/carbon[1.26.3, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.4, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.5, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.6, 2.20.0].
    - Can only install one of: nesbot/carbon[1.27.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.28.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.29.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.29.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.29.2, 2.20.0].
    - Can only install one of: nesbot/carbon[1.30.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.31.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.31.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.32.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.33.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.34.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.34.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.34.2, 2.20.0].
    - Can only install one of: nesbot/carbon[1.34.3, 2.20.0].
    - Can only install one of: nesbot/carbon[1.34.4, 2.20.0].
    - Can only install one of: nesbot/carbon[1.35.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.35.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.36.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.36.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.36.2, 2.20.0].
    - Can only install one of: nesbot/carbon[1.37.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.37.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.38.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.38.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.38.2, 2.20.0].
    - Can only install one of: nesbot/carbon[1.38.3, 2.20.0].
    - Can only install one of: nesbot/carbon[1.38.4, 2.20.0].
    - Can only install one of: nesbot/carbon[1.39.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.22.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.22.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.23.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.24.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.24.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.24.2, 2.20.0].
    - Can only install one of: nesbot/carbon[1.25.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.25.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.25.3, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.0, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.1, 2.20.0].
    - Can only install one of: nesbot/carbon[1.26.2, 2.20.0].
    - Installation request for nesbot/carbon (locked at 2.20.0) -> satisfiable by nesbot/carbon[2.20.0].

Installation failed, reverting ./composer.json to its original content.
--------

**Comment by anderly** [comment]
@nsnvglobal,

Yes, we'll be updating the dependencies to support Carbon 2.0.

**Comment by nsnvglobal** [comment]
Thanks I'm looking forward to try you package when supporting Carbon 2.0

**Comment by Melcus** [comment]
Any progress on this issue ?

**Comment by Matthijs-Huisman** [comment]
Any chance this will be updated any time soon?

**Comment by tavy315** [comment]
They died.

**Comment by anderly** [comment]
Just bumped carbon version. Will release new package version this week.

**Comment by tavy315** [comment]
Perhaps (if not too much to ask) you can change `"illuminate/support": "^5.8"` to `"illuminate/support": "^5.8|^6.0"` to also support current laravel version.

**Comment by Axent96** [comment]
Any update information for this issue?

**Comment by anderly** [comment]
@tavy315 done.

**Comment by anderly** [comment]
Should be fixed in 0.3.0
