### ISSUE TITLE
ODataClient - Closure instead of IAuthenticationProvider

### ISSUE THREAD

**Issue by czlowiekpolar** [saintsystems/odata-client-php#36]
IAuthenticationProvider is never used, but it would be helpfull. Instead of Closure (in constructor's second argument) should be Callable object (then possible would be pass an object with __invoke method declared) or declared already IAuthenticationProvider interface.

**Comment by anderly** [comment]
@jzskyshop,

Good catch. `Closure` should be `IAuthenticationProvider` in constructor. It's referenced as such in the IODataClient interface and ODataClient in the comment type hints. PHP 7.4 will allow us to make these property types. So, it really should be that in the constructor.

**Comment by anderly** [comment]
Closed by eefe08e1bdd325d9f6b123ceb5149be7389d82bd
