### ISSUE TITLE
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: Method must be a non-empty string. in <em class="placeholder">GuzzleHttp\Psr7\Request-&gt;assertMethod()</em>

### ISSUE THREAD

**Issue by fazni** [saintsystems/odata-client-php#37]
Hello,

When i tried to  get a specific item from a collection by ID .
`    $odataServiceUrl = 'https://services.odata.org/V4/TripPinService';

    $odataClient = new ODataClient($odataServiceUrl);
    $person = $odataClient->from('People')->find('russellwhyte');
    echo "Hello, I am $person->FirstName ";`
the system returned :

The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">InvalidArgumentException</em>: Method must be a non-empty string. in <em class="placeholder">GuzzleHttp\Psr7\Request-&gt;assertMethod()</em> (line <em class="placeholder">148</em> of <em class="placeholder">/vendor/guzzlehttp/psr7/src/Request.php</em>).

Thanks
Said

**Comment by Mastertrap21** [comment]
My pull request (https://github.com/saintsystems/odata-client-php/pull/35) fixes that, but it is not accepted yet :(

**Comment by fazni** [comment]
Thank you i used your pull request as Patch it worked for me.
Patch uri : [https://github.com/saintsystems/odata-client-php/commit/100fc79c0682604cffbd6e8a3e0fadfe2b0bd580.patch](https://github.com/saintsystems/odata-client-php/commit/100fc79c0682604cffbd6e8a3e0fadfe2b0bd580.patch)

**Comment by anderly** [comment]
Closed by #35
