### ISSUE TITLE
"Resource cannot be found"

### ISSUE THREAD

**Issue by Luc45** [saintsystems/odata-client-php#39]
First of all, thanks for your effort on this open-source project.

Secondly, I have zero experience with OData, I'm trying to fetch data from a third-party API, but I get different results when trying to query it with this library and when I enter the URL directly in the browser.

Example:

**Base URL:** `https://api.foo.com/odata`
**Entity:** `$odataClient->from('Providers')->get();`
**Authentication Callback:**
```
const TOKEN = '123456';

function(HttpRequestMessage $request) {
	$request->requestUri = $request->requestUri . '?token=' . self::TOKEN;
	return $request;
}
```

**Final request URL:** `https://api.foo.com/odata/Providers?token=123456`

Visiting this URL on the browser returns the expected results, while in code, the OData library returns a 404 - The resource cannot be found.

```
Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.foo.com/odata/Providers?token=123456` resulted in a `404 Not Found` response:
<!DOCTYPE html>
<html>
    <head>
        <title>The resource cannot be found.</title>
        <meta name="viewport" (truncated...)
 in /application/www/wp/foo/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /application/www/wp/foo/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /application/www/wp/foo/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /application/www/wp/foo/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /application/www/wp/foo/vendor/guzzlehttp/promises/src/TaskQueue.php(47): Guz
```

Am I missing something?

Thank you.

**Comment by anderly** [comment]
@Luc45,

My only thought is if the OData service doesn't return JSON, it wouldn't work, since this library currently only supports JSON. However, it seems to be from the 404 error, that's not the case, but rather an HTTP 404 Not Found error meaning some part of the URI is invalid.

You could write a simple test to make sure the library is generating the expected request. See the OData Request builder tests [here](https://github.com/saintsystems/odata-client-php/blob/master/tests/Query/BuilderTest.php
). You could write a similar one to assert that the expected URI (the one that is working in your browser) is the one returned by the library after the call to `toRequest()`. That might help track down the issue.

**Comment by Luc45** [comment]
Got it working.

I had to change `\SaintSystems\OData\ODataRequest::getDefaultHeaders` and remove the `RequestHeader::ODATA_VERSION => Constants::ODATA_VERSION,` array key.

Can we please address this on a next version? I could do a PR, but I don't know the implications of just removing that line since I know nothing about OData.

Thanks.

**Comment by anderly** [comment]
@Luc45,

Ok, this library assume a default of OData version 4.0. Sounds like you're on a different version. To fix that you have a couple of options to override the default. You can call `\SaintSystems\OData\ODataRequest->addHeaders(RequestHeader::ODATA_VERSION, '2.0')` and supply your service's OData version.

Or, you could simply remove the `RequestHeader::ODATA_VERSION` header in your authentication callback.

We'll probably look at supporting a .env for environment-specific overrides of this in the future, but those are your best options right now.

**Comment by Luc45** [comment]
Thanks, this worked:

```php
$odataClient = new ODataClient( $odataServiceUrl, function ( HttpRequestMessage $request ) {
	$headers = $request->headers;
	unset( $headers[ RequestHeader::ODATA_MAX_VERSION ] );
	unset( $headers[ RequestHeader::ODATA_VERSION ] );
	$request->headers    = $headers;

	return $request;
} );
```

**Comment by anderly** [comment]
Ideally, in the future, we'll still have our defaults but would support something like a `.env` file where you could define your overrides like so:

```
ODATA_MAX_VERSION=2.0
ODATA_VERSION =2.0
```

OR maybe something like this to remove those settings.

```
USE_ODATA_VERSION_HEADERS=false
```
