### ISSUE TITLE
Scalar Type hints

### ISSUE THREAD

**Issue by Zeromax** [saintsystems/odata-client-php#4]
In line https://github.com/saintsystems/odata-client-php/blob/8361f3f91d26abeac05635eabc680c80e0110b3d/src/Option.php#L7

```php
public function __construct(string $name, string $value)
```
This is a PHP7 feature. so increase the php version in composer.json or remove the hint here...

**Comment by Zeromax** [comment]
here too:
https://github.com/saintsystems/odata-client-php/blob/8361f3f91d26abeac05635eabc680c80e0110b3d/src/Uri.php#L36

**Comment by anderly** [comment]
Thanks, will do!

**Comment by Zeromax** [comment]
@anderly I can do this in my PR. Ok?

**Comment by anderly** [comment]
@zeromax perfect!

**Comment by Zeromax** [comment]
removed in ef4b40b
