### ISSUE TITLE
How to Post PUT PATCH? Can you give me an example?

### ISSUE THREAD

**Issue by 80302002** [saintsystems/odata-client-php#40]
How to Post PUT PATCH? Can you give me an example?

**Comment by anderly** [comment]
You should be able to use the `post`, `patch` and `delete` methods on the `ODataClient`.

**Example:**

```php
    $odataServiceUrl = 'https://services.odata.org/V4/TripPinService';

    $odataClient = new ODataClient($odataServiceUrl);

    $newPerson = $odataClient->post('People', [
        'FirstName' => 'John',
        'LastName' => 'Doe'
    ]);
```

**Comment by doomkers** [comment]
Patching is more complicated due no If-Match and good access to headers. I found only that solution:

        $oDataClient = new ODataClient($odataServiceUrl);
        $headers = ["If-Match" => "<etag value>"];
        $request = new ODataRequest(HttpMethod::PATCH, $oDataClient->getBaseUrl()
            . 'workflowCustomers({124312-12341234-123412})', $oDataClient, null);
        $request->attachBody($data);
        $request->addHeaders($headers);
        $request->execute();

**Comment by Jacq** [comment]
> You should be able to use the `post`, `patch` and `delete` methods on the `ODataClient`.
> 
> **Example:**
> 
> ```
>     $odataServiceUrl = 'https://services.odata.org/V4/TripPinService';
> 
>     $odataClient = new ODataClient($odataServiceUrl);
> 
>     $newPerson = $odataClient->post('People', [
>         'FirstName' => 'John',
>         'LastName' => 'Doe'
>     ]);
> ```

This gives an error on function attachBody($obj) from ODataRequest.php:159, in the else if:

` // JSON-encode the model object's property dictionary
        else if (method_exists($obj, 'getProperties')) {
            $class = get_class($obj);
            $class = explode("\\", $class);
            $model = strtolower(end($class));

            $body = $this->flattenDictionary($obj->getProperties());
            $this->requestBody = "{" . $model . ":" . json_encode($body) . "}";
        }
`
when trying to evaluate the body data (Array) with the method_exists function only valid for object | string

**Comment by joey-carlisle4** [comment]
Does this support posting a relationship's data as well?  I tried posting it under the relationship kev and it didn't work.
