### ISSUE TITLE
Insert method will not work

### ISSUE THREAD

**Issue by SergeyTrifonov** [saintsystems/odata-client-php#44]
https://github.com/saintsystems/odata-client-php/blob/454baac140360b8c534a1cb3f3636cdd5b8c6dcf/src/Query/Builder.php#L967

There is no "compileMethod" method in the interface, as in the class "Grammar".

**Comment by tonpascual** [comment]
`PHP Fatal error:  Uncaught Error: Call to undefined method SaintSystems\OData\Query\Grammar::compileInsert() in /srv/projects/php/fiberby/vendor/saintsystems/odata-client/src/Query/Builder.php:982
`
Same on my end.

**Comment by anderly** [comment]
Can't repro.

**Comment by anderly** [comment]
Closing due to age and can't repro.
