### ISSUE TITLE
How to make the multiple where conditions?

### ISSUE THREAD

**Issue by 80302002** [saintsystems/odata-client-php#46]
How to make the multiple where conditions?

**Comment by anderly** [comment]
See the [Filter a collection](https://github.com/saintsystems/odata-client-php/wiki/Example-Calls#filter-a-collection) section of the Wiki. There are several examples there.

You can chain multiple `where()` methods together, add `orWhere()` methods or pass an array of wheres like so:

```php
    $people = $odataClient->from('People')->where([
        ['FirstName','=','Russell'],
        ['LastName','=','Whyte'],
    ])->get();
```
