### ISSUE TITLE
Please add default header 'Accept: application/json'

### ISSUE THREAD

**Issue by BavoJanss** [saintsystems/odata-client-php#52]
Some systems like Microsoft Dynamics return XML by default and only return JSON upon request. Regarding the fact that this implementation only accepts JSON as valid format it should tell the remote end by Default.

In: \SaintSystems\OData\ODataRequest::getDefaultHeaders
Add: RequestHeader::ACCEPT =>  'application/json',

Keep up the good work, awesome implementation.

**Comment by anderly** [comment]
This fix is available in v0.5.1
