### ISSUE TITLE
Token URL

### ISSUE THREAD

**Issue by whande1992** [saintsystems/odata-client-php#53]
How do you insert the token parameter in the URL?

example: `https:\\api.site.com\tickets?token=e54fefe6f6ef4e64fe6ff6f4e4fe`

**Comment by anderly** [comment]
See #60. You can pass an httpProvider when you create a new client and control this behavior or [see here](https://github.com/saintsystems/odata-client-php/wiki/Example-Calls#initialize-the-odata-client-with-an-authentication-delegate) for the auth delegate option. You can customize this to append a token to the URL.
