### ISSUE TITLE
Illuminate/support ^7.0 for Laravel 7 compatibility

### ISSUE THREAD

**Issue by newtongamajr** [saintsystems/odata-client-php#54]
Hi everybody,
I need to update to Laravel 7 and I'm receiving the following errors when I try to do so:
 Problem 1
    - Installation request for saintsystems/odata-client ^0.3.0 -> satisfiable by saintsystems/odata-client[0.3.0].
    - Conclusion: remove laravel/framework v7.5.2
    - Conclusion: don't install laravel/framework v7.5.2
    - saintsystems/odata-client 0.3.0 requires illuminate/support ^5.8 || ^6.0 -> satisfiable by laravel/framework[5.8.x-dev, 6.x-dev], illuminate/support[5.8.x-dev, 6.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.2, v6.18.3, v6.18.4, v6.18.5, v6.18.6, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.5.2].
    - Can only install one of: laravel/framework[6.x-dev, v7.5.2].
    - don't install illuminate/support 5.8.x-dev|don't install laravel/framework v7.5.2
    - don't install illuminate/support 6.x-dev|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.11|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.12|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.14|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.15|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.17|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.18|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.19|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.2|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.20|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.22|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.24|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.27|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.28|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.29|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.3|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.30|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.31|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.32|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.33|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.34|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.35|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.36|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.4|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.8|don't install laravel/framework v7.5.2
    - don't install illuminate/support v5.8.9|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.0.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.0.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.0.2|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.0.3|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.0.4|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.1.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.10.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.11.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.12.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.13.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.13.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.14.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.15.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.15.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.16.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.17.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.17.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.2|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.3|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.4|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.5|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.18.6|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.2.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.3.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.4.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.5.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.5.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.5.2|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.6.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.6.1|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.6.2|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.7.0|don't install laravel/framework v7.5.2
    - don't install illuminate/support v6.8.0|don't install laravel/framework v7.5.2
    - Installation request for laravel/framework (locked at v7.5.2, required as ^7.0) -> satisfiable by laravel/framework[v7.5.2].
I hope to get your answer because now I have to develop some odata integrations and I'm at a rubicon point!

**Comment by whande1992** [comment]
Show us how is your package.json?

**Comment by renanwilliam** [comment]
Add pull request to cover Laravel 7.x

**Comment by anderly** [comment]
Closed by #56
