### ISSUE TITLE
V3 Service returns no data

### ISSUE THREAD

**Issue by tekook** [saintsystems/odata-client-php#57]
Hi there,
I'm currently starting to consume an oData service in php.
The Service I want to consume is oData v3.
odata-client-php does not return any data for the whole service.
I testet it with an different online service and same result. 

I tested https://services.odata.org/V3/OData/OData.svc/ and the results are the same.

Using: php-fpm-7.4.4-alpine

Code to reproduce:
```
$service_url = 'https://services.odata.org/V3/OData/OData.svc/'';
$client` = new ODataClient($service_url);
var_dump($client->from('Persons')->first());
```
Result: 
```
 SaintSystems\OData\Entity^ {#1178
  #primaryKey: "id"
  #perPage: 25
  #properties: []
  #original: []
  #relations: []
  #hidden: []
  #visible: []
  #appends: []
  #fillable: []
  #guarded: []
  #dates: []
  #dateFormat: null
  #casts: []
  #with: []
  -exists: null
  -entity: null
}
``` 
Any advice?

**Comment by tekook** [comment]
Or is v3 not supported?

**Comment by anderly** [comment]
@tekook v4 is currently only supported. No plans to support v3, but open to PRs if someone wants to implement it and send a patch.

**Comment by tekook** [comment]
> @tekook v4 is currently only supported. No plans to support v3, but open to PRs if someone wants to implement it and send a patch.

Damn, too bad. Back to dotnet it is then :-( 

Fyi, on https://www.odata.org/libraries/ this library is listed as supported "V1-V4".

![image](https://user-images.githubusercontent.com/976407/82352373-2afa2180-99fe-11ea-8597-ea6b4d2a8d58.png)
Maybe we should let it be marked as "v4" only.

Thanks for the quick reply

**Comment by anderly** [comment]
@tekook, thanks for letting us know about that. I believe someone else submitted that listing. I'll see if I can get it corrected to reflect V4.
