### ISSUE TITLE
find method when key is made up of two or more Properties,

### ISSUE THREAD

**Issue by k1mk** [saintsystems/odata-client-php#59]
What is the proper syntax here?

I can get it to work by doing 

`$client->get("Entity(prop1=1,prop2=2)");`

Is there some better way?

**Comment by anderly** [comment]
@k1mk we don't yet have this capability as the `find` method currently accepts only a single key. I'll leave this open and mark as enhancement.

**Comment by anderly** [comment]
@k1mk just fixed. Available in v0.5.2
