### ISSUE TITLE
NTLM auth

### ISSUE THREAD

**Issue by ZUBAT** [saintsystems/odata-client-php#60]
Tell me how can I use NTLM authorization when using your library?

**Comment by VincentBean** [comment]
When creating a new instance of the client you can pass a httpProvider.
For example:

    $httpProvider = new GuzzleHttpProvider();

    $this->httpProviderOptions = [
        'auth' => ['user', 'password', 'ntlm'],
    ];

    $this->odataClient = new ODataClient($odataServiceUrl, null, $httpProvider);

**Comment by DeanWard** [comment]
> When creating a new instance of the client you can pass a httpProvider. For example:
> 
> ```
> $httpProvider = new GuzzleHttpProvider();
> 
> $this->httpProviderOptions = [
>     'auth' => ['user', 'password', 'ntlm'],
> ];
> 
> $this->odataClient = new ODataClient($odataServiceUrl, null, $httpProvider);
> ```

How does $this->httpProviderOptions  get picked up?
