### ISSUE TITLE
Add parameter to all the requests

### ISSUE THREAD

**Issue by PieterCappelle** [saintsystems/odata-client-php#67]
Hi,

Is it possible to add a parameter to all the requests? I should add `$format=json` to every call the odataClient is creating. Thanks in advance!

**Comment by jessylennesl** [comment]
@PieterCappelle don't look like there's a simple way right now,

You can create a new class extending \SaintSystems\OData\GuzzleHttpProvider overriding the ```send()``` method.

Instanciate your class and give it to the \SaintSystems\OData\ODataClient::__construct : 

```php
$http = new YourGuzzleHttpProvider();
$client = new OdataClient($odataUrl, $authenticationProvider ?: null, $http);
```

**Comment by PieterCappelle** [comment]
Ok, thank you.
