### ISSUE TITLE
Multi Level Filter

### ISSUE THREAD

**Issue by WaelWafik** [saintsystems/odata-client-php#69]
Thank you for the great library, I am not really familiar with the codes but I tried 

$Properties = $odataClient->from('Property')->where([
      ['ListingKeyNumeric','=','1005476'],
	  ['NewConstructionYN','=','1']
  ])->get();

and it through the following error

{"error":{"code":400,"message":"Incompatible types."}}

The json looks like this:

`object(Illuminate\ Support\ Collection) #1322 (1) { ["items":protected]= > array(2) {
		[0] => object(SaintSystems\ OData\ Entity) #1338 (16) { ["primaryKey":protected]= > string(2)
		"id" ["perPage": protected] => int(25)["properties": protected] => array(238) {
			["ListingKeyNumeric"] => int(1005476)["AssociationFee"] => int(0)["RoomsTotal"] => int(0)["Stories"] => int(0)["BathroomsFull"] => int(0)["BathroomsHalf"] => int(0)["BathroomsThreeQuarter"] => int(0)["BathroomsPartial"] => int(0)["BathroomsTotalInteger"] => int(0)["BedroomsTotal"] => int(0)["CarportSpaces"] => int(0)["CoveredSpaces"] => int(0)["CoListAgentKeyNumeric"] => int(0)["CoListOfficeKeyNumeric"] => int(0)["CumulativeDaysOnMarket"] => int(183)["DaysOnMarket"] => int(183)["FireplacesTotal"] => int(0)["GarageSpaces"] => int(0)["ListAgentKeyNumeric"] => int(37053)["ListOfficeKeyNumeric"] => int(69693)["ListPrice"] => float(159000)["LeaseAmount"] => int(0)["LivingArea"] => int(0)["BuildingAreaTotal"] => int(0)["LotSizeAcres"] => float(0.37)["LotSizeSquareFeet"] => float(16117.2)["NumberOfBuildings"] => int(0)["NumberOfUnitsLeased"] => int(0)["NumberOfUnitsTotal"] => int(0)["LotSizeArea"] => float(0.37)["MainLevelBedrooms"] => int(0)["OriginalListPrice"] => float(159000)["ParkingTotal"] => int(0)["OpenParkingSpaces"] => int(0)["PhotosCount"] => int(0)["StreetNumberNumeric"] => int(1022)["TaxAnnualAmount"] => float(1)["YearBuilt"] => int(0)["YearBuiltEffective"] => int(0)["MobileLength"] => int(0)["MobileWidth"] => int(0)["BathroomsOneQuarter"] => int(0)["CapRate"] => int(0)["NumberOfPads"] => int(0)["StoriesTotal"] => int(0)["YearEstablished"] => int(0)["CoListAgentFirstName"] => NULL["CoListAgentFullName"] => string(0)
			"" ["CoListAgentKey"] => NULL["CoListAgentLastName"] => NULL["CoListAgentMiddleName"] => NULL["CoListAgentMlsId"] => NULL["CoListAgentStateLicense"] => NULL["CoListOfficeKey"] => NULL["CoListOfficeMlsId"] => NULL["CoListOfficeName"] => NULL["CopyrightNotice"] => string(57)
			"Copyright © UtahRealEstate.com. All Rights Reserved." ["CrossStreet"] => string(4)
			"1200" ["Exclusions"] => NULL["FrontageLength"] => string(4)
			"95.0" ["Inclusions"] => NULL["ListAgentFirstName"] => string(4)
			"Kaye" ["ListAgentFullName"] => string(16)
			"Kaye Christensen" ["ListAgentKey"] => string(5)
			"37053" ["ListAgentLastName"] => string(11)
			"Christensen" ["ListAgentMiddleName"] => string(0)
			"" ["ListAgentMlsId"] => string(5)
			"37053" ["ListOfficeKey"] => string(5)
			"69693" ["ListOfficeMlsId"] => string(5)
			"69693" ["ListOfficeName"] => string(15)
			"Showcase Realty" ["ListingId"] => string(7)
			"1005476" ["ListingKey"] => string(7)
			"1005476" ["OriginatingSystemID"] => string(9)
			"M00000628" ["OriginatingSystemKey"] => string(9)
			"M00000628" ["OriginatingSystemName"] => string(18)
			"UtahRealEstate.com" ["OtherParking"] => NULL["ParcelNumber"] => string(11)
			"11-046-0557" ["PostalCode"] => string(5)
			"84037" ["PublicRemarks"] => string(236)
			"Rare Find! Large,flat lot in desirable,established,East Kaysville neighborhood! HUGE 6+car garage/workshop already on property! Previous sale for over $200,000 fell through. Motivated owner taking a loss. Will finance with accept.terms." ["RVParkingDimensions"] => NULL["SourceSystemID"] => string(9)
			"M00000628" ["SourceSystemKey"] => string(9)
			"M00000628" ["SourceSystemName"] => string(18)
			"UtahRealEstate.com" ["StreetName"] => string(6)
			"OXFORD" ["StreetNumber"] => string(4)
			"1022" ["SubdivisionName"] => string(18)
			"KING CLARION HILLS" ["UnitNumber"] => string(3)
			"503" ["UnparsedAddress"] => string(16)
			"1022 E OXFORD DR" ["VirtualTourURLUnbranded"] => NULL["Zoning"] => string(13)
			"Single-Family" ["ZoningDescription"] => string(3)
			"RES" ["LotSizeDimensions"] => string(12)
			"95.0x0.0x0.0" ["Topography"] => string(13)
			"Terrain: Flat" ["BuilderName"] => NULL["DOH1"] => NULL["DOH2"] => NULL["DOH3"] => NULL["License1"] => NULL["License2"] => NULL["License3"] => NULL["Make"] => NULL["Model"] => NULL["ParkName"] => NULL["PostalCodePlus4"] => NULL["SerialU"] => NULL["SerialX"] => NULL["SerialXX"] => NULL["StreetAdditionalInfo"] => NULL["StreetSuffixModifier"] => NULL["WaterBodyName"] => NULL["AssociationYN"] => bool(false)["AttachedGarageYN"] => bool(false)["CarportYN"] => bool(false)["CoolingYN"] => bool(false)["FireplaceYN"] => bool(false)["GarageYN"] => bool(false)["HeatingYN"] => bool(false)["HorseYN"] => bool(true)["InternetAddressDisplayYN"] => bool(true)["SearchableYN"] => bool(true)["InternetEntireListingDisplayYN"] => bool(true)["OpenParkingYN"] => bool(false)["PoolPrivateYN"] => bool(false)["SeniorCommunityYN"] => bool(false)["SpaYN"] => bool(false)["ViewYN"] => bool(true)["NewConstructionYN"] => bool(false)["InternetAutomatedValuationDisplayYN"] => bool(false)["InternetConsumerCommentYN"] => bool(false)["LeaseConsideredYN"] => bool(false)["PropertyAttachedYN"] => bool(false)["WaterfrontYN"] => bool(false)["ContingentDate"] => NULL["ContractStatusChangeDate"] => string(10)
			"2011-06-24" ["ListingContractDate"] => string(10)
			"2010-12-23" ["OnMarketDate"] => string(10)
			"2010-12-23" ["PurchaseContractDate"] => string(10)
			"2011-06-20" ["ModificationTimestamp"] => string(20)
			"2020-12-02T16:43:03Z" ["OriginalEntryTimestamp"] => string(20)
			"2010-12-23T18:30:05Z" ["PhotosChangeTimestamp"] => NULL["PriceChangeTimestamp"] => NULL["StatusChangeTimestamp"] => NULL["AssociationFeeFrequency"] => string(0)
			"" ["City"] => string(9)
			"Kaysville" ["Country"] => string(2)
			"US" ["CountyOrParish"] => string(5)
			"Davis" ["DirectionFaces"] => string(5)
			"North" ["ElementarySchool"] => string(6)
			"Morgan" ["ElementarySchoolDistrict"] => string(5)
			"Davis" ["HighSchool"] => string(5)
			"Davis" ["HighSchoolDistrict"] => string(5)
			"Davis" ["ListingService"] => string(0)
			"" ["LivingAreaUnits"] => string(0)
			"" ["LotSizeUnits"] => string(0)
			"" ["MLSAreaMajor"] => string(32)
			"Kaysville; Fruit Heights; Layton" ["MiddleOrJuniorSchool"] => string(9)
			"Fairfield" ["MiddleOrJuniorSchoolDistrict"] => string(5)
			"Davis" ["MlsStatus"] => string(14)
			"Under Contract" ["PostalCity"] => string(9)
			"Kaysville" ["PropertySubType"] => string(11)
			"Residential" ["PropertyType"] => string(4)
			"Land" ["StandardStatus"] => string(7)
			"Pending" ["StateOrProvince"] => string(2)
			"UT" ["StreetDirPrefix"] => string(1)
			"E" ["StreetDirSuffix"] => string(1)
			"N" ["StreetSuffix"] => string(2)
			"DR" ["LivingAreaSource"] => string(0)
			"" ["YearBuiltSource"] => string(0)
			"" ["AccessibilityFeatures"] => string(0)
			"" ["Appliances"] => string(0)
			"" ["ArchitecturalStyle"] => string(0)
			"" ["AssociationAmenities"] => string(0)
			"" ["AssociationFeeIncludes"] => string(0)
			"" ["Basement"] => string(0)
			"" ["ConstructionMaterials"] => string(0)
			"" ["Cooling"] => string(0)
			"" ["DoorFeatures"] => string(0)
			"" ["ExteriorFeatures"] => string(25)
			"See Remarks,Out Buildings" ["Flooring"] => string(0)
			"" ["GreenBuildingVerificationType"] => string(0)
			"" ["Heating"] => string(0)
			"" ["InteriorFeatures"] => string(0)
			"" ["LaundryFeatures"] => string(0)
			"" ["ListingTerms"] => string(91)
			"See Remarks,Cash,Conventional,Lease Option,Owner 2nd,Seller Finance,Seller Will Subordinate" ["LotFeatures"] => string(74)
			"Curb & Gutter,Fenced: Part,Secluded,Sidewalks,View: Mountain,Terrain: Flat" ["OtherEquipment"] => string(0)
			"" ["ParkingFeatures"] => string(0)
			"" ["PatioAndPorchFeatures"] => string(0)
			"" ["PoolFeatures"] => string(0)
			"" ["PropertyCondition"] => string(13)
			"Blt./Standing" ["Roof"] => string(0)
			"" ["Sewer"] => string(0)
			"" ["Utilities"] => string(54)
			"See Remarks,Gas: Stubbed,Power: Stubbed,Sewer: Stubbed" ["Vegetation"] => string(0)
			"" ["View"] => string(0)
			"" ["WaterSource"] => string(0)
			"" ["WindowFeatures"] => string(0)
			"" ["CurrentUse"] => string(11)
			"Residential" ["Fencing"] => string(0)
			"" ["FireplaceFeatures"] => string(0)
			"" ["GreenEnergyGeneration"] => string(0)
			"" ["BodyType"] => string(0)
			"" ["BuildingFeatures"] => string(0)
			"" ["BusinessType"] => string(0)
			"" ["CommonWalls"] => string(0)
			"" ["CommunityFeatures"] => string(0)
			"" ["Electric"] => string(0)
			"" ["FoundationDetails"] => string(0)
			"" ["GreenEnergyEfficient"] => string(0)
			"" ["GreenIndoorAirQuality"] => string(0)
			"" ["GreenLocation"] => string(0)
			"" ["GreenSustainability"] => string(0)
			"" ["GreenWaterConservation"] => string(0)
			"" ["Levels"] => string(0)
			"" ["OtherStructures"] => string(0)
			"" ["PossibleUse"] => string(0)
			"" ["RentIncludes"] => string(0)
			"" ["RoadFrontageType"] => string(0)
			"" ["RoadSurfaceType"] => string(0)
			"" ["RoomType"] => string(0)
			"" ["Skirt"] => string(0)
			"" ["SpaFeatures"] => string(0)
			"" ["SpecialListingConditions"] => string(0)
			"" ["StructureType"] => string(0)
			"" ["UnitTypeType"] => string(0)
			"" ["WaterfrontFeatures"] => string(0)
			"" ["GeoLocation"] => NULL["BasementFinished"] => int(0)["ConstStatus"] => NULL["PowerProductionSolarYearInstall"] => int(0)["SolarFinanceCompany"] => NULL["SolarLeasingCompany"] => NULL["SolarOwnership"] => NULL["PowerProductionType"] => string(0)
			"" ["LevelData"] => string(1059)
			"levb_bathfull:0,levb_bathhalf:0,levb_bathtq:0,levb_bed:0,levb_den:0,levb_dining_f:0,levb_dining_s:0,levb_famroom:0,levb_fireplace:0,levb_formalliving:0,levb_kitchen_b:0,levb_kitchen_k:0,levb_laundry:0,levb_sqf:0,lev1_bathfull:0,lev1_bathhalf:0,lev1_bathtq:0,lev1_bed:0,lev1_den:0,lev1_dining_f:0,lev1_dining_s:0,lev1_famroom:0,lev1_fireplace:0,lev1_formalliving:0,lev1_kitchen_b:0,lev1_kitchen_k:0,lev1_laundry:0,lev1_sqf:0,lev2_bathfull:0,lev2_bathhalf:0,lev2_bathtq:0,lev2_bed:0,lev2_den:0,lev2_dining_f:0,lev2_dining_s:0,lev2_famroom:0,lev2_fireplace:0,lev2_formalliving:0,lev2_kitchen_b:0,lev2_kitchen_k:0,lev2_laundry:0,lev2_sqf:0,lev3_bathfull:0,lev3_bathhalf:0,lev3_bathtq:0,lev3_bed:0,lev3_den:0,lev3_dining_f:0,lev3_dining_s:0,lev3_famroom:0,lev3_fireplace:0,lev3_formalliving:0,lev3_kitchen_b:0,lev3_kitchen_k:0,lev3_laundry:0,lev3_sqf:0,lev4_bathfull:0,lev4_bathhalf:0,lev4_bathtq:0,lev4_bed:0,lev4_den:0,lev4_dining_f:0,lev4_dining_s:0,lev4_famroom:0,lev4_fireplace:0,lev4_formalliving:0,lev4_kitchen_b:0,lev4_kitchen_k:0,lev4_laundry:0,lev4_sqf:0" ["AboveGradeFinishedArea"] => int(0)["MasterBedroomLevel"] => string(0)
			"" ["IrrigationWaterRightsAcres"] => int(0)
		}["original": protected] => array(0) {}["relations": protected] => array(0) {}["hidden": protected] => array(0) {}["visible": protected] => array(0) {}["appends": protected] => array(0) {}["fillable": protected] => array(0) {}["guarded": protected] => array(0) {}["dates": protected] => array(0) {}["dateFormat": protected] => NULL["casts": protected] => array(0) {}["with": protected] => array(0) {}["exists": "SaintSystems\OData\Entity": private] => NULL["entity": "SaintSystems\OData\Entity": private] => NULL
	}
}
}`

**Comment by anderly** [comment]
Have you tried passing the numeric filter values as integers and not strings (i.e. remove the quotes around them)?

**Comment by WaelWafik** [comment]
Yeah same error

**Comment by anderly** [comment]
Unable to repro.
