### ISSUE TITLE
Builder->expand

### ISSUE THREAD

**Issue by Zeromax** [saintsystems/odata-client-php#7]
In this method there are a few mistakes.

- [ ] Two unused arguments: `$ref = false, $count = false`
- [x] The class `ExpandClause`  does not exist or there is a missing package? - fixed in https://github.com/saintsystems/odata-client-php/pull/8/commits/dfb3ed3402cb3443e3ad6442c4a0124f0811c97f#diff-bc4e6493f8d57ecd9362965a01af9bbcL7
- [x] The field `$this->expands` is not defined - fixed in https://github.com/saintsystems/odata-client-php/pull/8/commits/dfb3ed3402cb3443e3ad6442c4a0124f0811c97f#diff-e1377d46375e2197b5102fa2a9a492c8R156
- [ ] `$where` is undefined

**Comment by anderly** [comment]
Yes, this method still needs to be flushed out. Maybe we could remove for now. I need to add ExpandClause as this will eventually support OData expand properties.

**Comment by Zeromax** [comment]
Ah ok. Thougt its may be forgotten ;).
Is it possible to hava a channel to chat? Cause I do not want to full fill tickets with questions like this.

**Comment by anderly** [comment]
adam.anderly on Skype

**Comment by anderly** [comment]
Reopening and changing name to "Implement Builder->expand". The Builder->expand functionality needs to be implemented and is not yet functional.
