### ISSUE TITLE
Where in list

### ISSUE THREAD

**Issue by solokhind** [saintsystems/odata-client-php#70]
As of OData 4.01, the in statement is supported.

Here is the example from their documentation: 

> Example 56: all products whose name value is ‘Milk’ or ‘Cheese’:
> 
> http://host/service/Products?$filter=Name in ('Milk', 'Cheese')

http://docs.oasis-open.org/odata/odata/v4.01/csprd02/part2-url-conventions/odata-v4.01-csprd02-part2-url-conventions.html#_Toc486261685

Is there a functionality for this in this library? Thank you

**Comment by anderly** [comment]
Have you tried $client->where("Field", "contains", "foo")?

**Comment by ds620107** [comment]
This is a little different, I'm not trying to see if "field" contains "foo". I'm trying to see if "field" value exists in list. In the OData example, you're checking to see if Name equals "Milk" or "Cheese". 

I know I can use the `orWhere` method for this, but it is inefficient.

**Comment by anderly** [comment]
@ds620107,

I see. I'm going to see if we can get this implemented using whereIn() similar to Laravel query builder whereIn method.

Signature would be like `$client->whereIn('Name', ['Milk','Cheese'])`

Let me know if that would achieve what you're looking for.

**Comment by ds620107** [comment]
Yes, that would work. Thanks!

**Comment by joey-carlisle4** [comment]
any update?

**Comment by shaedrich** [comment]
I'd need that, too. So, I'm looking forward to it being implemented

**Comment by n8rowley** [comment]
I'd like to add my voice to those hoping this is still coming

**Comment by anderly** [comment]
Closed by #117

**Comment by anderly** [comment]
Closed by #117

**Comment by anderly** [comment]
See tests [here](https://github.com/saintsystems/odata-client-php/pull/117/files#diff-812a99d33113a0c841bee903bffe2356feaec248b3de5a93fb2c47630559e44a for example usage.
