### ISSUE TITLE
PHP  not working

### ISSUE THREAD

**Issue by alkankaya** [saintsystems/odata-client-php#71]
( ! ) Fatal error: Uncaught InvalidArgumentException: Method must be a non-empty string. in C:\wamp\www\vendor\guzzlehttp\psr7\src\Request.php on line 149
--

<?php

require_once __DIR__ . '/vendor/autoload.php';

use SaintSystems\OData\ODataClient;
class UsageExample
{
	public function __construct()
	{
		$odataServiceUrl = 'http://erptntapi.ecozum.com/api';

		    // Access token retrieved from an oauth provider
    //$accessToken = '';
    $odataClient = new ODataClient($odataServiceUrl, function($request) {

        // OAuth Bearer Token Authorization
        $request->headers['Authorization'] = 'Application eyJhbGciOiJodHRw.G9nVHlwZSI6MX1dfQ.EqMUZqQOZ5qJ_Zfas41bG3rKw';
	});
		// Retrieve all entities from the "People" Entity Set
		$people = $odataClient->from('/BankAccounts/GetErpBankAccounts')->get();

	echo "Hello, I am". $people;

		// Want to only select a few properties/columns?
		//$people = $odataClient->from('People')->select('FirstName','LastName')->get();
	}
}

$example = new UsageExample();

?>

**Comment by anderly** [comment]
Can you share a more complete example and where your $odataClient is instantiated?

Sounds like maybe the root url hasn't been setup, but can't tell without seeing more code.

**Comment by alkankaya** [comment]
`<?php

require_once __DIR__ . '/vendor/autoload.php';


use SaintSystems\OData\ODataClient;
class UsageExample
{
	public function __construct()
	{
		$odataServiceUrl = 'http://erptntapi.ecozum.com/api/';
$odataClient = new ODataClient($odataServiceUrl);

	
    $odataClient = new ODataClient($odataServiceUrl, function($request) {

      
        $request->headers['Authorization'] = 'Application eyJhbGciOiJodHRwOi8vd3d3****.iTG9nVH****.EqMUZqQOZ5qJ****';
	});
	
		$people = $odataClient->from('BankAccounts/GetErpBankAccounts')->get();


	}
}

$example = new UsageExample();`
![Php_Showing](https://user-images.githubusercontent.com/36801455/104482256-c5cfed80-55d7-11eb-88c8-519813bb6d8c.jpg)
![Odata](https://user-images.githubusercontent.com/36801455/104482304-d84a2700-55d7-11eb-9e04-44f2510eb762.png)


I access through the application (Postman),

**Comment by anderly** [comment]
Unable to repro.
