### ISSUE TITLE
how to update an existing records

### ISSUE THREAD

**Issue by ravatsinh** [saintsystems/odata-client-php#87]
Can you please give me example 
how we can update existing record value 

i can post to odata than record is got created but not getting how to update an existing records

**Comment by anderly** [comment]
You can use the `patch` [method](/blob/master/src/ODataClient.php#L235-L237) for this:

**Comment by cweiske** [comment]
Example:
```php
$oDataClient->patch(
    'contacts(' . $contactUuid . ')',
    [
        'lastname' => 'Dummy'
    ]
);
```
