### ISSUE TITLE
Post method not working

### ISSUE THREAD

**Issue by baldhadhaval08** [saintsystems/odata-client-php#90]
I'm trying to use post method for insert data. But somehow It's inserting hyphen `-` value for that field. I tried it with different field. Below is my code.

```
$postData = ['job_name' => 'Test'];
$newjob = $odataClient->post('job_applications', $postData);
```

@anderly Can you help me that what I'm missing.

**Comment by tavy315** [comment]
Not sure I understand your problem, but you can check the code from https://github.com/saintsystems/odata-client-php/blob/master/src/ODataRequest.php#L152 to see how it encodes the posted data, basically it does json_encode for your array.

**Comment by baldhadhaval08** [comment]
Yes I fixed it. thank you.
