### ISSUE TITLE
oData v2 - need to pass $format=json always

### ISSUE THREAD

**Issue by darkomni1** [saintsystems/odata-client-php#92]
Hello!

I noticed that when having to connect to an oData v2 service, the default format being returned is in a XML. As this needs a json format, is there a way to basically always set $format=json on all calls?

**Comment by anderly** [comment]
This is typically controlled by the `Accept` header, which this library sends as `application/json`. If you're not getting JSON back, it may be that the OData service you're calling doesn't support JSON.
