### ISSUE TITLE
Where not contains 

### ISSUE THREAD

**Issue by cooperRjp** [saintsystems/odata-client-php#99]
Hi,

Does anyone know how to implement a does not contains, for example get all products where product_title does not contain "DISCONTINUED"?

I thought it might have been ->where('product_title', '!contains', 'DISCONTINUED') but that doesn't work. I looked at the Grammar code but I couldn't see anything .

**Comment by anderly** [comment]
Closed by a1a5d5

**Comment by anderly** [comment]
Closed by a1a5d57
